export const ERROR_CODE = {
  NO_PERMISSION: 'NO_PERMISSION',
  NOT_FOUND: 'NOT_FOUND',
  PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND',
  PROJECT_FULL: 'PROJECT_FULL',
  ALREADY_CLAIMED: 'ALREADY_CLAIMED',
  NOT_CLAIMED: 'NOT_CLAIMED',
  CLAIM_CANCEL_EXPIRED: 'CLAIM_CANCEL_EXPIRED',
  INVALID_STATUS: 'INVALID_STATUS',
  INVALID_PROJECT: 'INVALID_PROJECT',
  INVALID_POSITION: 'INVALID_POSITION',
  INVALID_ACTION: 'INVALID_ACTION',
  INVALID_JSON: 'INVALID_JSON',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_TYPE_NOT_ALLOWED: 'FILE_TYPE_NOT_ALLOWED',
  NETWORK_ERROR: 'NETWORK_ERROR',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR'
} as const;

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];

export const ERROR_MESSAGE: Record<string, string> = {
  [ERROR_CODE.NO_PERMISSION]: '你没有权限执行此操作',
  [ERROR_CODE.NOT_FOUND]: '资源不存在',
  [ERROR_CODE.PROJECT_NOT_FOUND]: '档期不存在',
  [ERROR_CODE.PROJECT_FULL]: '该岗位已被认领满',
  [ERROR_CODE.ALREADY_CLAIMED]: '你已经认领过该项目',
  [ERROR_CODE.NOT_CLAIMED]: '你尚未认领该岗位',
  [ERROR_CODE.CLAIM_CANCEL_EXPIRED]: '认领已超过 10 分钟，请联系管理员处理',
  [ERROR_CODE.INVALID_STATUS]: '当前状态暂不能执行此操作',
  [ERROR_CODE.INVALID_PROJECT]: '档期信息不完整',
  [ERROR_CODE.INVALID_POSITION]: '岗位不存在或无需认领',
  [ERROR_CODE.INVALID_ACTION]: '审核动作无效',
  [ERROR_CODE.INVALID_JSON]: '请求数据格式错误',
  [ERROR_CODE.FILE_TOO_LARGE]: '文件大小不能超过 20MB',
  [ERROR_CODE.FILE_TYPE_NOT_ALLOWED]: '仅支持 PDF、Word、PPT 文件',
  [ERROR_CODE.NETWORK_ERROR]: '网络异常，请稍后重试',
  [ERROR_CODE.UNKNOWN_ERROR]: '操作失败，请稍后重试'
};

export function getErrorMessage(code?: string, fallback = ERROR_MESSAGE.UNKNOWN_ERROR) {
  if (!code) return fallback;
  return ERROR_MESSAGE[code] || fallback;
}
