<template>
  <view class="page-shell"><view class="page-hero"><view class="ink-nav"><text class="nav-back" @click="goBack">‹</text>报销进度</view></view>
    <view class="content-layer safe-bottom">
      <view class="submit-card" @click="goSubmit"><view><text class="submit-title">提交新的报销</text><text class="submit-copy">填写报销事项、金额与关联项目</text></view><text class="submit-arrow">›</text></view>
      <view v-if="loading" class="state-card">正在加载报销记录...</view><view v-else-if="!items.length" class="state-card">暂无报销记录</view>
      <view v-for="item in items" :key="item._id" class="record-card"><view class="record-copy"><text class="record-title">{{ item.title }}</text><text class="record-meta">{{ item.project_name || '未关联项目' }} · {{ formatTime(item.created_at) }}</text><text v-if="item.note" class="record-note">{{ item.note }}</text><text v-if="item.review_comment" class="review-comment">审核意见：{{ item.review_comment }}</text></view><view class="record-side"><text class="amount">¥{{ item.amount }}</text><text class="status" :class="item.status">{{ statusText(item.status) }}</text></view></view>
    </view>
  </view>
</template>
<script setup lang="ts">
import { ref } from 'vue'; import { onShow } from '@dcloudio/uni-app'; import { getReimbursements } from '@/api/user';
const items=ref<any[]>([]);const loading=ref(false);const goBack=()=>uni.navigateBack();const goSubmit=()=>uni.navigateTo({url:'/pages/mine/reimbursement-submit'});const formatTime=(value:number)=>new Date(value).toLocaleDateString('zh-CN');const statusText=(status:string)=>({pending:'待审核',approved:'已通过，待打款',rejected:'已驳回',paid:'已打款'}[status]||status);const load=async()=>{loading.value=true;try{items.value=await getReimbursements()}catch{uni.showToast({title:'报销记录加载失败',icon:'none'})}finally{loading.value=false}};onShow(load);
</script>
<style lang="scss" scoped>
@import '@/styles/variables.scss';@import '@/styles/mixins.scss';.page-hero{@include ink-header(184rpx);padding:64rpx 34rpx 38rpx;box-sizing:border-box}.nav-back{position:absolute;left:0;font-size:48rpx;line-height:1}.submit-card{display:flex;align-items:center;gap:16rpx;padding:27rpx 28rpx;margin-bottom:24rpx;border-radius:$radius-md;background:linear-gradient(135deg,$ink-blue,$ink-blue-deep);color:#fff}.submit-title,.submit-copy{display:block}.submit-title{font-size:29rpx;font-weight:800}.submit-copy{margin-top:7rpx;color:rgba(255,255,255,.76);font-size:23rpx}.submit-arrow{margin-left:auto;font-size:38rpx}.record-card,.state-card{@include soft-card;display:flex;align-items:center;gap:18rpx;padding:26rpx;margin-bottom:18rpx}.state-card{justify-content:center;color:$text-secondary}.record-copy{flex:1;min-width:0}.record-title,.record-meta,.record-note,.review-comment{display:block}.record-title{color:$text-primary;font-size:28rpx;font-weight:800}.record-meta,.record-note,.review-comment{margin-top:8rpx;color:$text-secondary;font-size:22rpx;line-height:1.45}.record-note{color:$text-muted}.review-comment{color:$red}.record-side{display:flex;flex-direction:column;align-items:flex-end;gap:10rpx}.amount{color:$ink-blue;font-size:28rpx;font-weight:800}.status{padding:6rpx 12rpx;border-radius:999rpx;background:$amber-bg;color:#94601d;font-size:21rpx}.status.approved,.status.paid{background:$green-bg;color:$green}.status.rejected{background:$red-bg;color:$red}
</style>
