<template>
  <view class="page-shell">
    <view class="page-hero"><view class="ink-nav"><text class="nav-back" @click="goBack">‹</text>档期管理<text class="publish-link" @click="goPublish">发布</text></view></view>
    <view class="content-layer safe-bottom">
      <view v-if="permissionDenied" class="state-card"><text class="state-title">仅管理员可管理档期</text><text class="state-copy">请在“我的”切换为管理员身份。</text></view>
      <block v-else>
        <scroll-view class="filter-scroll" scroll-x><view class="filters"><text v-for="item in filters" :key="item.key" class="filter" :class="{active:activeFilter===item.key}" @click="activeFilter=item.key">{{ item.name }}</text></view></scroll-view>
        <view v-if="loading" class="state-card">正在加载档期...</view><view v-else-if="!filtered.length" class="state-card">暂无符合条件的档期</view>
        <view v-for="item in filtered" :key="item._id" class="project-card">
          <view class="card-main" @click="goDetail(item._id)"><view><text class="project-title">{{ item.title }}</text><text class="project-meta">{{ item.datetime }} · {{ item.location }}</text></view><text class="pill" :class="statusTone(item.project_status)">{{ statusText(item.project_status) }}</text></view>
          <view class="card-footer"><text>负责人：{{ item.leader?.name || '待认领' }}</text><text>岗位：{{ memberCount(item) }}/{{ totalCount(item) }}</text><view class="edit-button" @click="edit(item._id)">编辑</view></view>
        </view>
      </block>
    </view>
  </view>
</template>
<script setup lang="ts">
import { computed,ref } from 'vue';import { onShow } from '@dcloudio/uni-app';import { getAdminProjects } from '@/api/project';import { login } from '@/api/user';import { useUserStore } from '@/stores/user';
const userStore=useUserStore();const loading=ref(false);const permissionDenied=ref(false);const projects=ref<any[]>([]);const activeFilter=ref('all');const filters=[{key:'all',name:'全部'},{key:'pending',name:'待处理'},{key:'recruiting',name:'招募中'},{key:'finished',name:'已结束'}];
const filtered=computed(()=>projects.value.filter((item)=>{if(activeFilter.value==='pending')return ['pending_claim','pending_review','revision_required'].includes(item.project_status);if(activeFilter.value==='recruiting')return ['recruiting','locked','completion_pending'].includes(item.project_status);if(activeFilter.value==='finished')return ['completed','cancelled'].includes(item.project_status);return true;}));
const statusText=(status:string)=>({pending_claim:'待认领',pending_review:'待审核',revision_required:'需修改',recruiting:'招募中',locked:'已锁定',completion_pending:'待完成确认',completed:'已完成',cancelled:'已取消'}[status]||status);const statusTone=(status:string)=>['recruiting','completed','locked'].includes(status)?'green':['pending_claim','pending_review','revision_required','completion_pending'].includes(status)?'amber':'red';const memberCount=(project:any)=>Object.values(project.positions||{}).reduce((n:number,position:any)=>n+(position.members||[]).length,0);const totalCount=(project:any)=>Object.values(project.positions||{}).reduce((n:number,position:any)=>n+Number(position.total||0),0);const goBack=()=>uni.navigateBack();const goPublish=()=>uni.navigateTo({url:'/pages/admin/publish'});const goDetail=(id:string)=>uni.navigateTo({url:`/pages/project/detail?id=${id}`});const edit=(id:string)=>uni.navigateTo({url:`/pages/admin/project-edit?id=${id}`});const load=async()=>{loading.value=true;permissionDenied.value=false;try{if(!userStore.userInfo)userStore.setUser(await login());if(!userStore.isAdmin){permissionDenied.value=true;return}projects.value=await getAdminProjects()}catch{uni.showToast({title:'档期加载失败',icon:'none'})}finally{loading.value=false}};onShow(load);
</script>
<style lang="scss" scoped>@import '@/styles/variables.scss';@import '@/styles/mixins.scss';.page-hero{@include ink-header(184rpx);padding:64rpx 34rpx 38rpx;box-sizing:border-box}.nav-back{position:absolute;left:0;font-size:48rpx;line-height:1}.publish-link{position:absolute;right:0;color:rgba(255,255,255,.88);font-size:25rpx}.filter-scroll{white-space:nowrap;margin-bottom:22rpx}.filters{display:inline-flex;gap:14rpx}.filter{padding:12rpx 22rpx;border-radius:999rpx;background:rgba(31,78,95,.07);color:$text-secondary;font-size:24rpx}.filter.active{background:$ink-blue;color:#fff}.project-card,.state-card{@include soft-card;padding:26rpx;margin-bottom:18rpx}.state-card{color:$text-secondary;text-align:center}.state-title,.state-copy{display:block}.state-title{color:$text-primary;font-size:30rpx;font-weight:800}.state-copy{margin-top:12rpx;font-size:24rpx}.card-main{display:flex;align-items:flex-start;justify-content:space-between;gap:16rpx}.project-title,.project-meta{display:block}.project-title{color:$text-primary;font-size:29rpx;font-weight:800}.project-meta{margin-top:9rpx;color:$text-secondary;font-size:23rpx}.card-footer{display:flex;align-items:center;gap:16rpx;margin-top:20rpx;padding-top:17rpx;border-top:1rpx solid rgba(31,78,95,.08);color:$text-muted;font-size:22rpx}.edit-button{margin-left:auto;padding:9rpx 17rpx;border-radius:999rpx;background:rgba(31,78,95,.08);color:$ink-blue;font-size:23rpx;font-weight:700}</style>
